[package]
name = "yser"
version = "0.1.0"
edition = "2021"

[features]
lmdb = ["dep:heed3"]
rocksdb = ["dep:rocksdb"]

[dependencies]
thiserror = "2.0.9"
bytes = "1.9.0"
zerocopy = { version = "0.8.14", features = ["derive", "simd"] }
heed3 = { version = "0.21.0", features = ["raw_value"], optional = true }
rocksdb = { version = "0.23.0", features = ["lz4"], optional = true }