[package]
name = "ysr"
version = "0.1.0"
edition = "2021"

[features]
lmdb = ["dep:heed"]
rocksdb = ["dep:rocksdb"]

[dependencies]
thiserror = "2.0.9"
bytes = "1.9.0"
zerocopy = { version = "0.8.14", features = ["derive", "simd"] }
heed = { version = "0.21.0", optional = true }
rocksdb = { version = "0.23.0", features = [], optional = true }
smallvec = { version = "1.13.2", features = ["const_generics", "const_new", "union", "write"] }
serde = { version = "1.0", features = ["rc", "alloc", "derive"] }
serde_json = { version = "1.0", features = ["alloc"] }
twox-hash = "2.1.0"

[dev-dependencies]
tempfile = "3.15.0"
simple-base64 = "0.23.2"